"""Shared constants for the synthetic demo dataset (Phase 7B).

Everything in this package is SYNTHETIC_DEMO ONLY. It is generated data shaped
like railway maintenance planning inputs and is never claimed to be live Indian
Railways data.
"""

from datetime import datetime, timezone

# ------------------------------------------------------------------- identity

SYNTHETIC_DEMO = "SYNTHETIC_DEMO"
SYNTHETIC_DEMO_DISCLAIMER = (
    "SYNTHETIC_DEMO: all data generated by this package is fabricated, "
    "deterministic demo data. It is NOT live Indian Railways data and must not "
    "be represented as such."
)

# ----------------------------------------------------------------- departments

DEPARTMENT_ENGINEERING = "Engineering"
DEPARTMENT_TRACTION_DISTRIBUTION = "Traction Distribution"
DEPARTMENT_SIGNALLING_TELECOMMUNICATION = "Signal & Telecommunication"

ALL_DEPARTMENTS = [
    DEPARTMENT_ENGINEERING,
    DEPARTMENT_TRACTION_DISTRIBUTION,
    DEPARTMENT_SIGNALLING_TELECOMMUNICATION,
]

# ------------------------------------------------------------------- horizon

#: Fixed planning horizon used by the demo dataset (deterministic anchor).
DEMO_HORIZON_START = datetime(2026, 1, 12, 0, 0, tzinfo=timezone.utc)
DEMO_HORIZON_END = datetime(2026, 1, 19, 0, 0, tzinfo=timezone.utc)
DEMO_HORIZON_DAYS = 7

#: Fixed "generated at" stamp so dataset JSON is byte-identical across runs.
DEMO_GENERATED_AT = datetime(2026, 1, 11, 6, 0, tzinfo=timezone.utc)

# -------------------------------------------------------------------- scale

DATASET_SCALE = {
    "corridors": 20,
    "assets": 50,
    "tasks": 100,
    "defects": 50,
    "train_movements": 100,
    "goods_forecasts": 50,
    "resources": 30,
    "block_requests": 100,
}

__all__ = [
    "ALL_DEPARTMENTS",
    "DATASET_SCALE",
    "DEMO_GENERATED_AT",
    "DEMO_HORIZON_DAYS",
    "DEMO_HORIZON_END",
    "DEMO_HORIZON_START",
    "DEPARTMENT_ENGINEERING",
    "DEPARTMENT_SIGNALLING_TELECOMMUNICATION",
    "DEPARTMENT_TRACTION_DISTRIBUTION",
    "SYNTHETIC_DEMO",
    "SYNTHETIC_DEMO_DISCLAIMER",
]