import json
from pathlib import Path
from datetime import datetime, timedelta

def generate_synthetic_demo_data():
    now = datetime.utcnow()
    tasks = [
        # Scenario 1: Critical overdue track defect
        {
            "request_id": "REQ-TMS-2026-001",
            "department": "ENGINEERING",
            "asset_id": "RAIL-SEC-AB-KM412",
            "asset_type": "RAIL_FRACTURE",
            "section": "SECTION_A_B",
            "location": "KM_412/12",
            "work_type": "Deep Screening & Rail Packing",
            "description": "Critical overdue rail fracture repair reported by TMS track geometry car",
            "duration_minutes": 180,
            "criticality": 95.0,
            "urgency": 90.0,
            "defect_severity": 88.0,
            "overdue_days": 14,
            "failure_probability": 0.85,
            "safety_impact": 95.0,
            "train_exposure": 85.0,
            "operational_impact": 80.0,
            "preferred_start": (now + timedelta(hours=2)).isoformat(),
            "preferred_end": (now + timedelta(hours=5)).isoformat(),
            "required_resources": ["BCM_MACHINE", "CIVIL_CREW_12"],
            "block_type": "CORRIDOR_BLOCK",
            "status": "PENDING_AI_EVALUATION"
        },
        # Scenario 2: High failure probability but not overdue
        {
            "request_id": "REQ-TMS-2026-002",
            "department": "ENGINEERING",
            "asset_id": "RAIL-SEC-EF-KM12",
            "asset_type": "RAIL_FRACTURE",
            "section": "SECTION_E_F",
            "location": "KM_12/04",
            "work_type": "Ultrasonic Flaw Detection Fix",
            "description": "Internal rail flaw detected by USFD sensor; non-overdue but high failure probability (0.90)",
            "duration_minutes": 150,
            "criticality": 90.0,
            "urgency": 70.0,
            "defect_severity": 85.0,
            "overdue_days": 0,
            "failure_probability": 0.90,
            "safety_impact": 90.0,
            "train_exposure": 60.0,
            "operational_impact": 70.0,
            "preferred_start": (now + timedelta(hours=6)).isoformat(),
            "preferred_end": (now + timedelta(hours=8.5)).isoformat(),
            "required_resources": ["USFD_TEAM", "CIVIL_CREW_6"],
            "block_type": "CORRIDOR_BLOCK",
            "status": "PENDING_AI_EVALUATION"
        },
        # Scenario 3 & 4 & 5: Engineering + Signalling + Traction 3-Department Candidate on SECTION_A_B
        {
            "request_id": "REQ-SMMS-2026-003",
            "department": "SIGNALLING",
            "asset_id": "SIG-PT-SEC-AB-SW04",
            "asset_type": "POINT_SWITCH",
            "section": "SECTION_A_B",
            "location": "KM_412/20",
            "work_type": "Point Machine Overhauling",
            "description": "Signalling point machine overhauling on Section A-B (Candidate with REQ-001)",
            "duration_minutes": 120,
            "criticality": 88.0,
            "urgency": 65.0,
            "defect_severity": 45.0,
            "overdue_days": 3,
            "failure_probability": 0.25,
            "safety_impact": 70.0,
            "train_exposure": 80.0,
            "operational_impact": 60.0,
            "preferred_start": (now + timedelta(hours=2, minutes=30)).isoformat(),
            "preferred_end": (now + timedelta(hours=4, minutes=30)).isoformat(),
            "required_resources": ["SIG_CREW_4"],
            "block_type": "SHADOW_BLOCK",
            "status": "PENDING_AI_EVALUATION"
        },
        {
            "request_id": "REQ-TDMS-2026-004",
            "department": "TRACTION",
            "asset_id": "OHE-CAT-SEC-AB-SPAN12",
            "asset_type": "OHE_CATENARY",
            "section": "SECTION_A_B",
            "location": "KM_413/05",
            "work_type": "Cantilever & Insulator Inspection",
            "description": "Traction OHE inspection on Section A-B (Completes 3-department candidate cluster)",
            "duration_minutes": 90,
            "criticality": 85.0,
            "urgency": 50.0,
            "defect_severity": 30.0,
            "overdue_days": 0,
            "failure_probability": 0.10,
            "safety_impact": 65.0,
            "train_exposure": 75.0,
            "operational_impact": 40.0,
            "preferred_start": (now + timedelta(hours=2, minutes=15)).isoformat(),
            "preferred_end": (now + timedelta(hours=3, minutes=45)).isoformat(),
            "required_resources": ["OHE_TOWER_CAR"],
            "block_type": "SHADOW_BLOCK",
            "status": "PENDING_AI_EVALUATION"
        },
        # Scenario 6: Same section but incompatible work types (Heavy Track Renewal vs Live Testing)
        {
            "request_id": "REQ-TMS-2026-005",
            "department": "ENGINEERING",
            "asset_id": "RAIL-SEC-AB-KM450",
            "asset_type": "TRACK_GEOMETRY",
            "section": "SECTION_A_B",
            "location": "KM_450/00",
            "work_type": "Heavy Ballast Cleaning",
            "description": "Heavy machinery ballast cleaning requiring total section power cut",
            "duration_minutes": 240,
            "criticality": 75.0,
            "urgency": 60.0,
            "defect_severity": 50.0,
            "overdue_days": 5,
            "failure_probability": 0.20,
            "safety_impact": 60.0,
            "train_exposure": 80.0,
            "operational_impact": 75.0,
            "preferred_start": (now + timedelta(hours=10)).isoformat(),
            "preferred_end": (now + timedelta(hours=14)).isoformat(),
            "required_resources": ["BCM_MACHINE"],
            "block_type": "CORRIDOR_BLOCK",
            "status": "PENDING_AI_EVALUATION"
        },
        # Scenario 7: Same section but non-overlapping time windows (14 hours later)
        {
            "request_id": "REQ-SMMS-2026-006",
            "department": "SIGNALLING",
            "asset_id": "SIG-AXLE-SEC-AB-KM420",
            "asset_type": "SIGNAL_INTERLOCKING",
            "section": "SECTION_A_B",
            "location": "KM_420/10",
            "work_type": "Axle Counter Maintenance",
            "description": "Night shift axle counter calibration on Section A-B (14 hours after REQ-001)",
            "duration_minutes": 60,
            "criticality": 60.0,
            "urgency": 40.0,
            "defect_severity": 20.0,
            "overdue_days": 0,
            "failure_probability": 0.05,
            "safety_impact": 40.0,
            "train_exposure": 30.0,
            "operational_impact": 20.0,
            "preferred_start": (now + timedelta(hours=18)).isoformat(),
            "preferred_end": (now + timedelta(hours=19)).isoformat(),
            "required_resources": ["SIG_CREW_2"],
            "block_type": "SHADOW_BLOCK",
            "status": "PENDING_AI_EVALUATION"
        },
        # Scenario 8: Different section (SECTION_C_D)
        {
            "request_id": "REQ-BDMS-2026-007",
            "department": "ENGINEERING",
            "asset_id": "BRIDGE-SEC-CD-KM88",
            "asset_type": "BRIDGE_EXPANSION",
            "section": "SECTION_C_D",
            "location": "KM_88/04",
            "work_type": "Bridge Expansion Joint Replacement",
            "description": "Bridge girder joint inspection and bearing greasing",
            "duration_minutes": 150,
            "criticality": 92.0,
            "urgency": 75.0,
            "defect_severity": 70.0,
            "overdue_days": 2,
            "failure_probability": 0.30,
            "safety_impact": 85.0,
            "train_exposure": 50.0,
            "operational_impact": 65.0,
            "preferred_start": (now + timedelta(hours=4)).isoformat(),
            "preferred_end": (now + timedelta(hours=6.5)).isoformat(),
            "required_resources": ["BRIDGE_CREW_8"],
            "block_type": "CORRIDOR_BLOCK",
            "status": "PENDING_AI_EVALUATION"
        },
        # Scenario 9: Low-priority routine maintenance (Priority Score < 40)
        {
            "request_id": "REQ-BDMS-2026-008",
            "department": "ENGINEERING",
            "asset_id": "FENCE-SEC-GH-KM05",
            "asset_type": "TRACK_GEOMETRY",
            "section": "SECTION_G_H",
            "location": "KM_05/12",
            "work_type": "Boundary Wall Painting & Cleaning",
            "description": "Routine station approach boundary wall cosmetic maintenance",
            "duration_minutes": 120,
            "criticality": 15.0,
            "urgency": 10.0,
            "defect_severity": 5.0,
            "overdue_days": 0,
            "failure_probability": 0.01,
            "safety_impact": 10.0,
            "train_exposure": 20.0,
            "operational_impact": 10.0,
            "preferred_start": (now + timedelta(hours=24)).isoformat(),
            "preferred_end": (now + timedelta(hours=26)).isoformat(),
            "required_resources": ["CIVIL_PAINT_CREW"],
            "block_type": "CORRIDOR_BLOCK",
            "status": "PENDING_AI_EVALUATION"
        },
        # Scenario 10: High train exposure task
        {
            "request_id": "REQ-TMS-2026-009",
            "department": "ENGINEERING",
            "asset_id": "RAIL-HIGH-TRAIN-KM01",
            "asset_type": "RAIL_FRACTURE",
            "section": "BUSY_MAIN_TRUNK",
            "location": "KM_01/10",
            "work_type": "Emergency Rail Weld",
            "description": "High density main trunk line rail weld repair (Train exposure = 98.0)",
            "duration_minutes": 90,
            "criticality": 95.0,
            "urgency": 85.0,
            "defect_severity": 80.0,
            "overdue_days": 1,
            "failure_probability": 0.50,
            "safety_impact": 90.0,
            "train_exposure": 98.0,
            "operational_impact": 90.0,
            "preferred_start": (now + timedelta(hours=3)).isoformat(),
            "preferred_end": (now + timedelta(hours=4.5)).isoformat(),
            "required_resources": ["WELDING_TEAM"],
            "block_type": "CORRIDOR_BLOCK",
            "status": "PENDING_AI_EVALUATION"
        },
        # Scenario 11: Zero train exposure branch line task
        {
            "request_id": "REQ-TMS-2026-010",
            "department": "ENGINEERING",
            "asset_id": "RAIL-BRANCH-KM02",
            "asset_type": "TRACK_GEOMETRY",
            "section": "BRANCH_LINE_X",
            "location": "KM_02/01",
            "work_type": "Sleeper Replacement",
            "description": "Branch line wooden sleeper replacement; zero passenger train exposure",
            "duration_minutes": 180,
            "criticality": 30.0,
            "urgency": 30.0,
            "defect_severity": 15.0,
            "overdue_days": 0,
            "failure_probability": 0.05,
            "safety_impact": 25.0,
            "train_exposure": 0.0,
            "operational_impact": 15.0,
            "preferred_start": (now + timedelta(hours=12)).isoformat(),
            "preferred_end": (now + timedelta(hours=15)).isoformat(),
            "required_resources": ["CIVIL_CREW_4"],
            "block_type": "CORRIDOR_BLOCK",
            "status": "PENDING_AI_EVALUATION"
        },
        # Scenario 12: High operational impact task
        {
            "request_id": "REQ-TMS-2026-011",
            "department": "ENGINEERING",
            "asset_id": "POINT-HUB-KM00",
            "asset_type": "POINT_SWITCH",
            "section": "MAJOR_JUNCTION_HUB",
            "location": "KM_00/01",
            "work_type": "Junction Diamond Crossover Overhaul",
            "description": "Major junction crossover repair creating severe network throughput impact (100.0)",
            "duration_minutes": 240,
            "criticality": 90.0,
            "urgency": 80.0,
            "defect_severity": 75.0,
            "overdue_days": 4,
            "failure_probability": 0.40,
            "safety_impact": 80.0,
            "train_exposure": 95.0,
            "operational_impact": 100.0,
            "preferred_start": (now + timedelta(hours=5)).isoformat(),
            "preferred_end": (now + timedelta(hours=9)).isoformat(),
            "required_resources": ["JUNCTION_SPECIALIST_TEAM"],
            "block_type": "CORRIDOR_BLOCK",
            "status": "PENDING_AI_EVALUATION"
        },
        # Scenario 13: Low operational impact task
        {
            "request_id": "REQ-SMMS-2026-012",
            "department": "SIGNALLING",
            "asset_id": "SIG-CAB-SIDETRACK",
            "asset_type": "SIGNAL_INTERLOCKING",
            "section": "FREIGHT_SIDING_Y",
            "location": "KM_00/50",
            "work_type": "Relay Cabinet Inspection",
            "description": "Siding relay cabinet check with minimal main line impact (Operational impact = 5.0)",
            "duration_minutes": 45,
            "criticality": 40.0,
            "urgency": 20.0,
            "defect_severity": 10.0,
            "overdue_days": 0,
            "failure_probability": 0.02,
            "safety_impact": 30.0,
            "train_exposure": 10.0,
            "operational_impact": 5.0,
            "preferred_start": (now + timedelta(hours=7)).isoformat(),
            "preferred_end": (now + timedelta(hours=7, minutes=45)).isoformat(),
            "required_resources": ["SIG_CREW_1"],
            "block_type": "SHADOW_BLOCK",
            "status": "PENDING_AI_EVALUATION"
        },
        # Scenario 14: High safety impact task
        {
            "request_id": "REQ-TDMS-2026-013",
            "department": "TRACTION",
            "asset_id": "OHE-HIGH-VOLT-SPAN",
            "asset_type": "OHE_CATENARY",
            "section": "SECTION_I_J",
            "location": "KM_55/12",
            "work_type": "Emergency OHE Wire Snap Repair",
            "description": "High voltage traction wire spark hazard; critical safety consequence (98.0)",
            "duration_minutes": 120,
            "criticality": 85.0,
            "urgency": 95.0,
            "defect_severity": 92.0,
            "overdue_days": 7,
            "failure_probability": 0.75,
            "safety_impact": 98.0,
            "train_exposure": 85.0,
            "operational_impact": 75.0,
            "preferred_start": (now + timedelta(hours=1)).isoformat(),
            "preferred_end": (now + timedelta(hours=3)).isoformat(),
            "required_resources": ["OHE_TOWER_CAR"],
            "block_type": "EMERGENCY_BLOCK",
            "status": "PENDING_AI_EVALUATION"
        },
        # Scenario 15: Low safety impact task
        {
            "request_id": "REQ-BDMS-2026-014",
            "department": "ENGINEERING",
            "asset_id": "DRAIN-SEC-KL-KM02",
            "asset_type": "TRACK_GEOMETRY",
            "section": "SECTION_K_L",
            "location": "KM_02/40",
            "work_type": "Side Culvert Ditch Cleaning",
            "description": "Track side drainage clearing; zero passenger safety threat (Safety impact = 10.0)",
            "duration_minutes": 180,
            "criticality": 20.0,
            "urgency": 15.0,
            "defect_severity": 10.0,
            "overdue_days": 0,
            "failure_probability": 0.01,
            "safety_impact": 10.0,
            "train_exposure": 30.0,
            "operational_impact": 15.0,
            "preferred_start": (now + timedelta(hours=15)).isoformat(),
            "preferred_end": (now + timedelta(hours=18)).isoformat(),
            "required_resources": ["CLEANING_CREW"],
            "block_type": "CORRIDOR_BLOCK",
            "status": "PENDING_AI_EVALUATION"
        }
    ]

    output_dir = Path(__file__).resolve().parent.parent / "data"
    output_dir.mkdir(parents=True, exist_ok=True)
    file_path = output_dir / "synthetic_demo_tasks.json"

    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(tasks, f, indent=2)

    print(f"Generated 15 synthetic demo tasks at {file_path}")

if __name__ == "__main__":
    generate_synthetic_demo_data()
