class ReasonCodes:
    HIGH_ASSET_CRITICALITY = "HIGH_ASSET_CRITICALITY"
    SAFETY_RELATED_DEFECT = "SAFETY_RELATED_DEFECT"
    OVERDUE_MAINTENANCE = "OVERDUE_MAINTENANCE"
    CRITICAL_DEFECT_SEVERITY = "CRITICAL_DEFECT_SEVERITY"
    HIGH_FAILURE_RISK = "HIGH_FAILURE_RISK"
    HEAVY_TRAIN_EXPOSURE = "HEAVY_TRAIN_EXPOSURE"
    SEVERE_OPERATIONAL_IMPACT = "SEVERE_OPERATIONAL_IMPACT"
    ROUTINE_MAINTENANCE = "ROUTINE_MAINTENANCE"
