import React, { useState, useMemo } from 'react';
import {
  Sparkles,
  Check,
  X,
  RotateCcw,
  AlertTriangle,
  Clock,
  Info,
} from 'lucide-react';
import { PageHeader } from '@/components/common/PageHeader';
import { StatusBadge } from '@/components/common/StatusBadge';
import { DepartmentBadge } from '@/components/common/DepartmentBadge';
import { FilterBar } from '@/components/common/FilterBar';
import { LoadingState } from '@/components/common/LoadingState';
import { EmptyState } from '@/components/common/EmptyState';
import {
  useAIRecommendations,
  useAcceptRecommendation,
  useRejectRecommendation,
  useOverrideRecommendation,
} from '@/hooks';
import type { RecommendationType, RecommendationStatus } from '@/types/ai';
import type { Department } from '@/types/asset';
import { formatTime, formatDate, formatDuration } from '@/utils';

export const AIRecommendationsPage: React.FC = () => {
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedType, setSelectedType] = useState<string>('ALL');
  const [selectedStatus, setSelectedStatus] = useState<string>('ALL');
  const [selectedDept, setSelectedDept] = useState<string>('ALL');

  const filters = useMemo(() => {
    return {
      type: selectedType !== 'ALL' ? (selectedType as RecommendationType) : undefined,
      status: selectedStatus !== 'ALL' ? (selectedStatus as RecommendationStatus) : undefined,
      department: selectedDept !== 'ALL' ? (selectedDept as Department) : undefined,
    };
  }, [selectedType, selectedStatus, selectedDept]);

  const { data: recommendations, isLoading, isError, refetch } = useAIRecommendations(filters);

  const acceptMutation = useAcceptRecommendation();
  const rejectMutation = useRejectRecommendation();
  const overrideMutation = useOverrideRecommendation();

  const filteredRecs = useMemo(() => {
    if (!recommendations) return [];
    if (!searchQuery.trim()) return recommendations;
    const q = searchQuery.toLowerCase();
    return recommendations.filter(
      (r) =>
        r.recommendationId.toLowerCase().includes(q) ||
        r.type.toLowerCase().includes(q) ||
        r.reasons.some((reason) => reason.toLowerCase().includes(q))
    );
  }, [recommendations, searchQuery]);

  const hasActiveFilters =
    Boolean(searchQuery) ||
    selectedType !== 'ALL' ||
    selectedStatus !== 'ALL' ||
    selectedDept !== 'ALL';

  const handleClearFilters = () => {
    setSearchQuery('');
    setSelectedType('ALL');
    setSelectedStatus('ALL');
    setSelectedDept('ALL');
  };

  const handleAccept = (recommendationId: string) => {
    acceptMutation.mutate({ recommendationId, reason: 'Accepted by Chief Controller' });
  };

  const handleReject = (recommendationId: string) => {
    rejectMutation.mutate({ recommendationId, reason: 'Rejected by Chief Controller' });
  };

  const handleOverride = (recommendationId: string) => {
    overrideMutation.mutate({ recommendationId, reason: 'Overridden with custom parameter' });
  };

  return (
    <div className="space-y-4">
      <PageHeader
        title="AI Optimization Recommendations"
        description="Prescriptive bundling and conflict resolution proposals generated by the optimization engine."
        icon={Sparkles}
        badge="SIMULATED DEMO"
      />

      {/* Mandatory Demo Disclaimer Banner */}
      <div className="p-3.5 rounded-lg bg-cyan-950/40 border border-cyan-500/30 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Info className="w-5 h-5 text-cyan-400 shrink-0" />
          <div>
            <p className="text-xs font-mono font-bold text-cyan-300">
              Simulated AI Recommendation — Demo
            </p>
            <p className="text-[11px] text-cyan-400/80">
              Heuristic prototype outputs illustrating automated shadow block bundling and corridor conflict mitigations.
            </p>
          </div>
        </div>
        <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-cyan-500/20 text-cyan-300 border border-cyan-500/30">
          Module 3 Integration
        </span>
      </div>

      <FilterBar
        searchQuery={searchQuery}
        onSearchChange={setSearchQuery}
        searchPlaceholder="Search recommendation ID, type, or reason..."
        hasActiveFilters={hasActiveFilters}
        onClearFilters={handleClearFilters}
        totalCount={recommendations?.length}
        filteredCount={filteredRecs.length}
      >
        <select
          value={selectedType}
          onChange={(e) => setSelectedType(e.target.value)}
          className="bg-slate-950 border border-slate-700/80 rounded-md px-2.5 py-1.5 text-xs text-slate-200 focus:outline-none focus:border-blue-500 font-mono"
        >
          <option value="ALL">All Recommendation Types</option>
          <option value="INTEGRATED_BLOCK">INTEGRATED_BLOCK</option>
          <option value="RESCHEDULE">RESCHEDULE</option>
          <option value="PRIORITIZE">PRIORITIZE</option>
          <option value="CONFLICT_RESOLUTION">CONFLICT_RESOLUTION</option>
          <option value="DEFER">DEFER</option>
          <option value="EMERGENCY_ACTION">EMERGENCY_ACTION</option>
        </select>

        <select
          value={selectedStatus}
          onChange={(e) => setSelectedStatus(e.target.value)}
          className="bg-slate-950 border border-slate-700/80 rounded-md px-2.5 py-1.5 text-xs text-slate-200 focus:outline-none focus:border-blue-500 font-mono"
        >
          <option value="ALL">All Statuses</option>
          <option value="PROPOSED">PROPOSED</option>
          <option value="ACCEPTED">ACCEPTED</option>
          <option value="REJECTED">REJECTED</option>
          <option value="OVERRIDDEN">OVERRIDDEN</option>
        </select>

        <select
          value={selectedDept}
          onChange={(e) => setSelectedDept(e.target.value)}
          className="bg-slate-950 border border-slate-700/80 rounded-md px-2.5 py-1.5 text-xs text-slate-200 focus:outline-none focus:border-blue-500 font-mono"
        >
          <option value="ALL">All Departments</option>
          <option value="ENGINEERING">Engineering</option>
          <option value="SNT">S&T</option>
          <option value="TRACTION">Traction</option>
        </select>
      </FilterBar>

      {isLoading ? (
        <LoadingState message="Fetching AI optimization proposals..." />
      ) : isError ? (
        <div className="p-6 rounded-lg bg-rose-500/10 border border-rose-500/30 text-center">
          <AlertTriangle className="w-6 h-6 text-rose-400 mx-auto mb-2" />
          <p className="text-xs text-rose-300">Failed to load AI recommendations.</p>
          <button
            onClick={() => refetch()}
            className="mt-3 px-3 py-1.5 rounded bg-rose-500/20 text-rose-300 text-xs font-mono"
          >
            Retry
          </button>
        </div>
      ) : filteredRecs.length === 0 ? (
        <EmptyState title="No AI recommendations found" description="Adjust your filters or query." />
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {filteredRecs.map((rec) => (
            <div
              key={rec.recommendationId}
              className="p-4 rounded-lg bg-slate-900/60 border border-slate-800 hover:border-slate-700 transition-all flex flex-col justify-between space-y-4"
            >
              <div>
                {/* Header */}
                <div className="flex items-center justify-between pb-2 border-b border-slate-800">
                  <div className="flex items-center gap-2">
                    <span className="font-mono font-bold text-sm text-cyan-400">{rec.recommendationId}</span>
                    <span className="px-2 py-0.5 rounded text-[10px] font-mono bg-cyan-500/10 text-cyan-300 border border-cyan-500/30 font-semibold">
                      {rec.type}
                    </span>
                  </div>
                  <StatusBadge status={rec.status} size="sm" />
                </div>

                {/* Departments Involved */}
                <div className="mt-3 flex items-center justify-between">
                  <div className="flex flex-wrap gap-1">
                    {rec.departments.map((d) => (
                      <DepartmentBadge key={d} department={d} size="sm" showIcon={false} />
                    ))}
                  </div>
                  <span className="text-[10px] font-mono text-slate-400">
                    {formatDate(rec.createdAt)}
                  </span>
                </div>

                {/* Proposed Window */}
                <div className="mt-3 p-2.5 rounded bg-slate-950/60 border border-slate-800 font-mono text-xs flex items-center justify-between">
                  <span className="text-slate-400 flex items-center gap-1.5">
                    <Clock className="w-3.5 h-3.5 text-blue-400" />
                    Proposed Slot:
                  </span>
                  <span className="text-slate-200 font-semibold">
                    {formatTime(rec.proposedWindow.startTime)} - {formatTime(rec.proposedWindow.endTime)} (
                    {formatDuration(rec.proposedWindow.durationMinutes)})
                  </span>
                </div>

                {/* Explanation / Reasons */}
                <div className="mt-3 space-y-1">
                  <span className="text-[10px] font-mono text-slate-400 uppercase font-semibold">
                    Optimization Rationale:
                  </span>
                  <ul className="list-disc list-inside text-xs text-slate-300 space-y-1">
                    {rec.reasons.map((r, i) => (
                      <li key={i}>{r}</li>
                    ))}
                  </ul>
                </div>

                {/* Affected tasks & Operational Impact */}
                <div className="mt-3 pt-2 border-t border-slate-800/80 grid grid-cols-2 gap-2 text-xs font-mono">
                  <div>
                    <span className="text-[10px] text-slate-400 uppercase">Affected Tasks:</span>
                    <div className="flex flex-wrap gap-1 mt-1">
                      {rec.affectedTaskIds.map((tid) => (
                        <span key={tid} className="text-[10px] px-1 py-0.2 rounded bg-blue-500/10 text-blue-300">
                          {tid}
                        </span>
                      ))}
                    </div>
                  </div>
                  <div className="text-right">
                    <span className="text-[10px] text-slate-400 uppercase">Operational Impact:</span>
                    <p className="text-slate-300 text-[11px] mt-1">
                      {rec.operationalImpact.trainsAffectedCount} trains affected ({rec.operationalImpact.totalDelayMinutes}m delay)
                    </p>
                  </div>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="pt-2 border-t border-slate-800 flex items-center justify-between font-mono text-xs">
                <span className="text-[10px] text-slate-400">Decision Control:</span>
                <div className="flex items-center gap-1.5">
                  {rec.status !== 'ACCEPTED' && (
                    <button
                      onClick={() => handleAccept(rec.recommendationId)}
                      disabled={acceptMutation.isPending}
                      className="px-2.5 py-1 rounded bg-emerald-600 text-white hover:bg-emerald-500 font-medium flex items-center gap-1 transition-colors"
                      title="Accept Recommendation"
                    >
                      <Check className="w-3.5 h-3.5" />
                      <span>Accept</span>
                    </button>
                  )}
                  {rec.status !== 'REJECTED' && (
                    <button
                      onClick={() => handleReject(rec.recommendationId)}
                      disabled={rejectMutation.isPending}
                      className="px-2.5 py-1 rounded bg-rose-500/10 text-rose-400 border border-rose-500/30 hover:bg-rose-500/20 flex items-center gap-1 transition-colors"
                      title="Reject Recommendation"
                    >
                      <X className="w-3.5 h-3.5" />
                      <span>Reject</span>
                    </button>
                  )}
                  {rec.status !== 'OVERRIDDEN' && (
                    <button
                      onClick={() => handleOverride(rec.recommendationId)}
                      disabled={overrideMutation.isPending}
                      className="px-2 py-1 rounded bg-slate-800 text-slate-400 hover:bg-slate-700 flex items-center gap-1 transition-colors"
                      title="Manual Override"
                    >
                      <RotateCcw className="w-3 h-3" />
                      <span>Override</span>
                    </button>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
export default AIRecommendationsPage;
